### ISSUE TITLE
Search engine: HTTP status 404 on some requests

### ISSUE THREAD

**Issue by Susticle** [PanoptikumIO/pan#12]
On some search requests a 404 is thrown.

Example:
A search for "sciencekompass" gives http status 404 with the text "This page could not be found! Did you mistype the url?"

A search for "sciencekompasp" gives http status 200 with the text "Sorry, nothing found."

**Comment by haslinger** [comment]
The search failed because of outdated entries in the search index. 

The search index is now being cleaned up and should be fine soon - not only for your example request, that is working already.

We need to automatically remove entries from the search on delete, which will be handled in #11.

**Comment by haslinger** [comment]
The automatic search index update is now in place. Feel free to create a new issue or reopen if you find any more strange search results.
