### ISSUE TITLE
"duration" of episode is given in different formats

### ISSUE THREAD

**Issue by Susticle** [PanoptikumIO/pan#35]
When collecting podcast data using the API different podcast episodes contain different formats in the duration field.

*Examples*

*Number of seconds*
https://panoptikum.io/jsonapi/podcasts/1202/

*hh:mm:ss*
https://panoptikum.io/jsonapi/podcasts/5/

Would it be a good idea to have just one format in the database?

**Comment by haslinger** [comment]
Would be nice, it's currently garbage in garbage out. So whatever is provided in the feed is stored in this text field. 
I didn't even try to do some normalization here, being burnt by the `publication_date` timestamp, where I currently parse using more than 60 regular expressions...
PRs are obviously welcome ;-)

**Comment by Susticle** [comment]
I searched for more information and this seems to be not so difficult as the publication_date. :-)

The [Apple Podcasts Connect Help](https://help.apple.com/itc/podcasts_connect/#/itcb54353390) says:

> The episode duration in hours, minutes, and seconds.
> 
> Specify one of the following formats for the <itunes:duration> tag value:
> * HH:MM:SS
> * H:MM:SS
> * MM:SS
> * M:SS
>
> Where H = hours, M = minutes, and S = seconds.
> 
> If you specify a single number as a value (without colons), Apple Podcasts displays the value as seconds. If you specify one colon, Apple Podcasts displays the number to the left as minutes and the number to the right as seconds. If you specify more then two colons, Apple Podcasts ignores the numbers farthest to the right.

**Comment by haslinger** [comment]
Our most favorite issues are the ones, where the requester contributes the necessary code him/herself. :-)
Resolved with: dce188dae390955c6006e59c9ac7f051a443ee45
