### ISSUE TITLE
Suggestion: Don't show "pro features" and "Payment information" box when pro account is still running for a while

### ISSUE THREAD

**Issue by Susticle** [PanoptikumIO/pan#46]
After login, the box "Unlock all pro features for one year pro for 12 EUR only!" with buttons "Pro features" and "Payment information" is displayed.

I suggest to not display this box so big when the pro account is still running for a long time. Maybe it can combined with the information "Pro account until" below the box.

For me, it happens from time to time, that I'm surprised and think: "Oh, is the year over already?" until I see the smaller hint below the box.

**Comment by haslinger** [comment]
That box should not be shown at all, when pro is still running. Have to look into this...

**Comment by haslinger** [comment]
Meanwhile, I see, why I did it that way. I wanted to trigger the users in trial period to upgrade.

It's way more friendly now: Rephrased, a bit more decent, and green for >30 left, yellow for >7 days left, then red.
