### ISSUE TITLE
Feature request: Make <title> more helpful

### ISSUE THREAD

**Issue by Susticle** [PanoptikumIO/pan#56]
At the moment, all pages of panoptikum.io just have the word "Panoptikum" in the html <title> element.

So if you have several windows/tabs with different panoptikum.io pages open, all tabs only show "Panoptikum" without further information.

It would be nice to have a hint on the viewed page in there, like:

- Podcast:
  "Sendegarten - Panoptikum"

- Episode:
  "Synthesizer madness - Panoptikum"

- Profile:
  "My profile - Panoptikum"

etc.

**Comment by haslinger** [comment]
Technical solution is injecting the metadata into the layout via the view. See https://stackoverflow.com/questions/42362376/phoenix-framework-page-titles-per-route for several approaches.

**Comment by haslinger** [comment]
Implemented on all views.
